services:
  postgres:
    image: postgres:16
    container_name: zero-plan-postgres
    environment:
      POSTGRES_DB: zero_plan
      POSTGRES_USER: zero_plan_user
      POSTGRES_PASSWORD: zero_plan_password
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U zero_plan_user -d zero_plan"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
